logging:
  level: DEBUG
  format: '%(asctime)s - %(levelname)s - %(message)s'
  handlers:
    - console:
        level: INFO
        formatter: simple
    - file:
        filename: 'logs/training.log'
        level: DEBUG
        formatter: detailed
  formatters:
    simple:
      format: '%(message)s'
    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
